# Generated by Django 4.2.3 on 2023-09-27 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(blank=True, max_length=50, null=True)),
                ('bankname', models.CharField(blank=True, max_length=50, null=True)),
                ('accountnumber', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='deposite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('accnumber', models.IntegerField(blank=True, null=True)),
                ('img', models.FileField(blank=True, upload_to='confirm/')),
                ('approved', models.BooleanField()),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(blank=True, max_length=50)),
                ('mins', models.IntegerField()),
                ('maxs', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=50)),
                ('img', models.FileField(blank=True, upload_to='confirm/')),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('accnumber', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('bankname', models.CharField(blank=True, max_length=50)),
                ('approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='userOnPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(max_length=50)),
                ('dateincrease', models.CharField(blank=True, max_length=90)),
                ('active', models.BooleanField()),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.plan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='inviteduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('invites', models.IntegerField(blank=True, null=True)),
                ('mine', models.IntegerField(blank=True, null=True)),
                ('date_reg', models.DateField(auto_now_add=True)),
                ('verified', models.BooleanField()),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('uuid', models.CharField(blank=True, max_length=50)),
                ('cardUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.carduser')),
                ('deposite', models.ManyToManyField(blank=True, to='app.deposite')),
                ('invited', models.ManyToManyField(blank=True, to='app.inviteduser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('withdraw', models.ManyToManyField(blank=True, to='app.withdraw')),
            ],
        ),
    ]
