# Generated by Django 2.0.13 on 2023-11-16 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accwithdra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(max_length=50)),
                ('accountnumber', models.CharField(blank=True, max_length=50)),
                ('bankname', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('disc', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='APIfetch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('nameS', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Btc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('img', models.FileField(blank=True, upload_to='btc')),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Btcpayin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('prof', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('btcname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Btc')),
            ],
        ),
        migrations.CreateModel(
            name='Depositchecking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('front', models.TextField(blank=True)),
                ('back', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kycdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(blank=True, max_length=50)),
                ('ZipCode', models.CharField(blank=True, max_length=50)),
                ('Nationality', models.CharField(blank=True, max_length=50)),
                ('City', models.CharField(blank=True, max_length=50)),
                ('Idname', models.CharField(blank=True, max_length=50)),
                ('AddressLine1', models.CharField(blank=True, max_length=50, null=True)),
                ('AddressLine2', models.CharField(blank=True, max_length=50, null=True)),
                ('front', models.TextField(blank=True, null=True)),
                ('back', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
                ('addressLine2', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inviteduser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useronplan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='useronplan',
            name='user',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='invites',
            new_name='AccountNUm',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='code',
            new_name='Currency',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='mine',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='deposite',
            old_name='name',
            new_name='accountnumber',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cardUser',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_reg',
        ),
        migrations.RemoveField(
            model_name='client',
            name='invited',
        ),
        migrations.RemoveField(
            model_name='deposite',
            name='accnumber',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='accnumber',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='bankname',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='name',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='number',
        ),
        migrations.AddField(
            model_name='client',
            name='Bdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='Pin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='Tancode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='scretanswer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='scretqestion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='typeAcc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deposite',
            name='bankname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deposite',
            name='disc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deposite',
            name='holdername',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deposite',
            name='statedecr',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='img',
            field=models.FileField(blank=True, upload_to='deposit/'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='cardUser',
        ),
        migrations.DeleteModel(
            name='inviteduser',
        ),
        migrations.DeleteModel(
            name='plan',
        ),
        migrations.DeleteModel(
            name='userOnPlan',
        ),
        migrations.AddField(
            model_name='kycdb',
            name='cardUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Client'),
        ),
        migrations.AddField(
            model_name='accwithdra',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Client'),
        ),
        migrations.AddField(
            model_name='client',
            name='depositeckecked',
            field=models.ManyToManyField(blank=True, to='app.Depositchecking'),
        ),
        migrations.AddField(
            model_name='client',
            name='userBtcpay',
            field=models.ManyToManyField(blank=True, to='app.Btcpayin'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='Accto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Accwithdra'),
        ),
    ]
