# Generated by Django 4.2.5 on 2023-11-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_accwithdra_id_alter_apifetch_id_alter_btc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='seftcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='swiftcode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deposite',
            name='BankAddress',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deposite',
            name='BankCountry',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deposite',
            name='Currency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deposite',
            name='swiftcode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='btcpayin',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositchecking',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
