# Generated by Django 4.2.5 on 2023-11-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_client_disabled_client_seftcode_client_swiftcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
