# Generated by Django 5.2.1 on 2025-05-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='AccountNUm',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Tancode',
            field=models.BigIntegerField(blank=True, max_length=50, null=True),
        ),
    ]
