# Generated by Django 5.2.1 on 2025-05-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_client_accountnum_alter_client_tancode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='AccountNUm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Tancode',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
